#!/usr/bin/env bash
# scaffold_project.sh
# Creates the full folder tree for SpeakUp Reading (IELTS Reading Trainer).
# Run once, then `cd ielts_reading_app` and `flutter create --project-name ielts_reading_app --platforms=android --org com.morshed .`

set -e

ROOT="ielts_reading_app"
mkdir -p "$ROOT"
cd "$ROOT"

# ---------- top-level ----------
mkdir -p assets/fonts assets/icons assets/images assets/lottie
mkdir -p docs scripts
mkdir -p firebase/functions/src
mkdir -p .github/workflows

# ---------- lib/ ----------
mkdir -p lib/core/{app,router,errors,network,storage,logging,utils}
mkdir -p lib/services/{gemini,firebase,cache}
mkdir -p lib/shared_widgets

# features
FEATURES=(onboarding auth api_key_setup diagnostic home reading vocabulary progress settings)
for f in "${FEATURES[@]}"; do
  mkdir -p "lib/features/$f/data"
  mkdir -p "lib/features/$f/domain"
  mkdir -p "lib/features/$f/presentation/widgets"
  mkdir -p "lib/features/$f/providers"
done

# ---------- test/ (mirrors lib/) ----------
mkdir -p test/core test/services
for f in "${FEATURES[@]}"; do
  mkdir -p "test/features/$f"
done

# ---------- placeholder files so the tree survives git ----------
PLACEHOLDERS=(
  "lib/main.dart|// Entry point. Initializes Firebase, Hive, Riverpod, GoRouter. See PRD §13.1"
  "lib/firebase_options.dart|// Generated by \`flutterfire configure\` — do not edit by hand."
  "lib/core/app/app.dart|// MaterialApp.router here."
  "lib/core/app/app_theme.dart|// Light + dark Material 3 themes."
  "lib/core/app/app_constants.dart|// App-wide constants (durations, sizes, etc.)."
  "lib/core/router/app_router.dart|// GoRouter with auth + api-key + diagnostic redirect logic. See PRD §13.2"
  "lib/core/router/route_names.dart|// Centralized route name constants."
  "lib/core/errors/app_exception.dart|// Typed app exceptions."
  "lib/core/errors/failure.dart|// Sealed Failure hierarchy for repositories."
  "lib/core/network/connectivity_service.dart|// Wraps connectivity_plus."
  "lib/core/storage/secure_storage_service.dart|// flutter_secure_storage wrapper. Gemini key lives here. See PRD §11"
  "lib/core/storage/hive_boxes.dart|// Box name constants + init helper."
  "lib/core/logging/logger.dart|// Thin wrapper around package:logger."
  "lib/core/utils/text_tokenizer.dart|// Splits passage into tappable word tokens + punctuation. Core of TappableText."
  "lib/core/utils/band_calculator.dart|// Raw score → IELTS band mapping."
  "lib/core/utils/extensions.dart|// Dart/Flutter extensions."
  "lib/services/gemini/gemini_service.dart|// Wrapper around google_generative_ai. See PRD §13.3"
  "lib/services/gemini/prompts.dart|// ALL Gemini prompts live here — referenced by name only."
  "lib/services/gemini/gemini_providers.dart|// Riverpod providers for GeminiService."
  "lib/services/firebase/auth_service.dart|// Firebase Auth + Google Sign-In."
  "lib/services/firebase/firestore_service.dart|// Typed Firestore access. UI never calls FirebaseFirestore directly."
  "lib/services/firebase/firebase_providers.dart|// Riverpod providers for auth + firestore."
  "lib/services/cache/word_cache_service.dart|// Firestore-backed + Hive-backed word definition cache."
  "lib/shared_widgets/app_button.dart|// Shared button."
  "lib/shared_widgets/app_scaffold.dart|// Shared scaffold with consistent padding + app bar."
  "lib/shared_widgets/loading_view.dart|// Shared loading state."
  "lib/shared_widgets/error_view.dart|// Shared error state with retry."
  "lib/shared_widgets/empty_view.dart|// Shared empty state."
)

# feature-specific placeholders
FEATURE_FILES=(
  "lib/features/onboarding/presentation/onboarding_page.dart|// First-run carousel (3 slides)."
  "lib/features/onboarding/presentation/widgets/onboarding_slide.dart|"
  "lib/features/onboarding/providers/onboarding_providers.dart|"

  "lib/features/auth/data/auth_repository.dart|"
  "lib/features/auth/domain/app_user.dart|// freezed model."
  "lib/features/auth/presentation/login_page.dart|// Google Sign-In UI."
  "lib/features/auth/presentation/widgets/google_signin_button.dart|"
  "lib/features/auth/providers/auth_providers.dart|"

  "lib/features/api_key_setup/data/api_key_repository.dart|// Validates key with a 1-token test call."
  "lib/features/api_key_setup/presentation/api_key_setup_page.dart|// Shows instructions from PRD §16."
  "lib/features/api_key_setup/presentation/widgets/key_help_card.dart|"
  "lib/features/api_key_setup/providers/api_key_providers.dart|"

  "lib/features/diagnostic/data/diagnostic_repository.dart|"
  "lib/features/diagnostic/domain/diagnostic_question.dart|"
  "lib/features/diagnostic/domain/diagnostic_result.dart|"
  "lib/features/diagnostic/presentation/diagnostic_intro_page.dart|"
  "lib/features/diagnostic/presentation/diagnostic_test_page.dart|"
  "lib/features/diagnostic/presentation/diagnostic_result_page.dart|"
  "lib/features/diagnostic/providers/diagnostic_providers.dart|"

  "lib/features/home/presentation/home_page.dart|// Recommended passage cards based on band."
  "lib/features/home/presentation/widgets/passage_card.dart|"
  "lib/features/home/providers/home_providers.dart|"

  "lib/features/reading/data/passage_repository.dart|"
  "lib/features/reading/domain/passage.dart|// freezed model."
  "lib/features/reading/domain/question.dart|// freezed model."
  "lib/features/reading/domain/answer.dart|"
  "lib/features/reading/presentation/passage_page.dart|// Passage view with TappableText."
  "lib/features/reading/presentation/questions_page.dart|"
  "lib/features/reading/presentation/result_page.dart|// Correctness + AI explanations (markdown)."
  "lib/features/reading/presentation/widgets/tappable_text.dart|// SIGNATURE WIDGET. See PRD §13.4"
  "lib/features/reading/presentation/widgets/word_definition_dialog.dart|// Dialog shown on word tap. See FR-WORD-03."
  "lib/features/reading/presentation/widgets/question_tile.dart|"
  "lib/features/reading/presentation/widgets/explanation_tile.dart|"
  "lib/features/reading/providers/reading_providers.dart|"

  "lib/features/vocabulary/data/vocabulary_repository.dart|"
  "lib/features/vocabulary/domain/saved_word.dart|"
  "lib/features/vocabulary/presentation/vocabulary_page.dart|"
  "lib/features/vocabulary/presentation/widgets/saved_word_tile.dart|"
  "lib/features/vocabulary/providers/vocabulary_providers.dart|"

  "lib/features/progress/data/progress_repository.dart|"
  "lib/features/progress/domain/progress_stats.dart|"
  "lib/features/progress/presentation/progress_page.dart|"
  "lib/features/progress/presentation/widgets/band_trend_chart.dart|// fl_chart usage."
  "lib/features/progress/providers/progress_providers.dart|"

  "lib/features/settings/presentation/settings_page.dart|"
  "lib/features/settings/presentation/widgets/settings_tile.dart|"
  "lib/features/settings/providers/settings_providers.dart|"
)

write_stub() {
  local path="$1"
  local note="$2"
  if [ ! -f "$path" ]; then
    if [ -n "$note" ]; then
      echo "$note" > "$path"
      echo "// TODO: implement" >> "$path"
    else
      echo "// TODO: implement" > "$path"
    fi
  fi
}

for item in "${PLACEHOLDERS[@]}"; do
  IFS='|' read -r path note <<<"$item"
  write_stub "$path" "$note"
done

for item in "${FEATURE_FILES[@]}"; do
  IFS='|' read -r path note <<<"$item"
  write_stub "$path" "$note"
done

# test placeholders (keeps dirs in git)
touch test/core/.gitkeep test/services/.gitkeep
for f in "${FEATURES[@]}"; do touch "test/features/$f/.gitkeep"; done

# ---------- pubspec.yaml ----------
cat > pubspec.yaml <<'YAML'
name: ielts_reading_app
description: SpeakUp Reading — IELTS Reading Trainer with AI-generated passages and Bangla word meanings.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State + routing
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.7

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  google_sign_in: ^6.2.1

  # Google AI
  google_generative_ai: ^0.4.6

  # Storage
  flutter_secure_storage: ^9.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # Misc
  http: ^1.2.2
  connectivity_plus: ^6.0.5
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  fl_chart: ^0.69.0
  flutter_markdown: ^0.7.3+1
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.3
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: NotoSansBengali
      fonts:
        - asset: assets/fonts/NotoSansBengali-Regular.ttf
        - asset: assets/fonts/NotoSansBengali-Bold.ttf
          weight: 700
YAML

# ---------- analysis_options.yaml ----------
cat > analysis_options.yaml <<'YAML'
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/firebase_options.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  plugins:
    - custom_lint

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    require_trailing_commas: true
    unawaited_futures: true
YAML

# ---------- build.yaml ----------
cat > build.yaml <<'YAML'
targets:
  $default:
    builders:
      freezed:
        options:
          generic_argument_factories: true
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: none
YAML

# ---------- .gitignore ----------
cat > .gitignore <<'GI'
# Flutter
.dart_tool/
.packages
.pub/
build/
.flutter-plugins
.flutter-plugins-dependencies
.metadata
pubspec.lock

# IDE
.idea/
.vscode/
*.iml

# Android
**/android/.gradle/
**/android/captures/
**/android/local.properties
**/android/**/GeneratedPluginRegistrant.java
**/android/app/debug
**/android/app/profile
**/android/app/release
**/android/key.properties
**/android/*.jks

# iOS
**/ios/Flutter/App.framework
**/ios/Flutter/Flutter.framework
**/ios/Flutter/Flutter.podspec
**/ios/Flutter/Generated.xcconfig
**/ios/Flutter/ephemeral
**/ios/Flutter/app.flx
**/ios/Flutter/app.zip
**/ios/Flutter/flutter_assets/
**/ios/Flutter/flutter_export_environment.sh
**/ios/ServiceDefinitions.json
**/ios/Runner/GeneratedPluginRegistrant.*

# Codegen
**/*.g.dart
**/*.freezed.dart
**/*.gr.dart

# Firebase (keep options only for local dev; ignore sensitive config)
google-services.json
GoogleService-Info.plist
firebase_app_id_file.json

# Env
.env
.env.local

# Misc
*.log
.DS_Store
GI

# ---------- .env.example ----------
cat > .env.example <<'ENV'
# No server-side env vars required for v1.
# The Gemini API key is provided by each end-user inside the app
# and stored locally via flutter_secure_storage — not via env files.
ENV

# ---------- firebase/firestore.rules ----------
cat > firebase/firestore.rules <<'RULES'
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {

    // Per-user data: owner-only
    match /users/{uid} {
      allow read, write: if request.auth != null && request.auth.uid == uid;

      match /{subcol}/{docId} {
        allow read, write: if request.auth != null && request.auth.uid == uid;
      }
    }

    // Shared caches: read for any signed-in user, write via admin/Cloud Functions only
    match /passages/{passageId} {
      allow read: if request.auth != null;
      allow write: if false;
    }

    match /wordDefinitions/{word} {
      allow read: if request.auth != null;
      allow write: if false;
    }
  }
}
RULES

cat > firebase/firestore.indexes.json <<'JSON'
{
  "indexes": [
    {
      "collectionGroup": "sessions",
      "queryScope": "COLLECTION",
      "fields": [
        { "fieldPath": "createdAt", "order": "DESCENDING" }
      ]
    },
    {
      "collectionGroup": "passages",
      "queryScope": "COLLECTION",
      "fields": [
        { "fieldPath": "band", "order": "ASCENDING" },
        { "fieldPath": "generatedAt", "order": "DESCENDING" }
      ]
    }
  ],
  "fieldOverrides": []
}
JSON

# ---------- Cloud Functions (optional) ----------
cat > firebase/functions/package.json <<'JSON'
{
  "name": "ielts-reading-functions",
  "description": "Optional Cloud Functions for passage seeding and moderation.",
  "engines": { "node": "20" },
  "main": "lib/index.js",
  "scripts": {
    "build": "tsc",
    "serve": "npm run build && firebase emulators:start --only functions",
    "deploy": "firebase deploy --only functions"
  },
  "dependencies": {
    "firebase-admin": "^12.0.0",
    "firebase-functions": "^5.0.0"
  },
  "devDependencies": {
    "typescript": "^5.4.0"
  },
  "private": true
}
JSON

cat > firebase/functions/src/index.ts <<'TS'
// Optional Cloud Functions. Not required for MVP.
// Use for: daily passage seeding, moderation of reported word meanings.
import { onRequest } from "firebase-functions/v2/https";

export const health = onRequest((_req, res) => {
  res.status(200).send("ok");
});
TS

# ---------- CI ----------
cat > .github/workflows/flutter_ci.yml <<'YML'
name: flutter_ci
on:
  push: { branches: [ main, develop ] }
  pull_request: { branches: [ main, develop ] }
jobs:
  analyze_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: flutter analyze
      - run: flutter test
YML

# ---------- docs ----------
cat > docs/ARCHITECTURE.md <<'MD'
# Architecture

See PRD §8. This file is a living document — expand here as decisions are made.

## Layering

```
presentation (UI)  →  providers (Riverpod)  →  repository  →  service (Gemini / Firestore)
```

The UI never imports `cloud_firestore` or `google_generative_ai` directly.
MD

cat > docs/DECISIONS.md <<'MD'
# Architecture Decision Records (ADRs)

## ADR-001: Bring-Your-Own-Key (BYOK) for Gemini
**Status:** Accepted
**Context:** Free-tier Gemini quota is per-key. Pooling all users under one key would run out fast.
**Decision:** Each end-user provides their own Gemini key in-app. Stored in flutter_secure_storage.
**Consequences:** Zero infra cost for the developer. Higher friction at onboarding — mitigated with in-app walkthrough.

## ADR-002: Riverpod over Bloc
**Status:** Accepted
**Decision:** Riverpod 2.x with code-gen.

## ADR-003: Feature-first folders
**Status:** Accepted
**Decision:** `lib/features/<name>/{data,domain,presentation,providers}`.
MD

cat > docs/PROMPTS.md <<'MD'
# Prompt library (mirror of lib/services/gemini/prompts.dart)

Maintain prompt versions here for review. Every prompt must request JSON output.

## word_definition (v1)
See PRD §10.1.

## passage_generation (v1)
See PRD §10.2.

## question_generation (v1)
TBD.

## diagnostic_grading (v1)
TBD.
MD

cat > docs/SMOKE_TESTS.md <<'MD'
# Smoke test checklist (manual, pre-release)

- [ ] Fresh install → Google Sign-In works
- [ ] Invalid Gemini key → user sees clear error, can retry
- [ ] Valid Gemini key → diagnostic intro loads
- [ ] Diagnostic test completes and persists result
- [ ] Home shows 3+ passage cards matched to the user's band
- [ ] Passage opens; tap any word → dialog shows Bangla + English meaning
- [ ] Cached word taps load in < 500 ms
- [ ] "Save word" writes to Firestore; appears in Vocabulary tab
- [ ] Questions screen scores correctly; explanations render markdown
- [ ] Progress dashboard reflects the new session
- [ ] Settings → sign out clears secure storage and returns to /login
MD

# ---------- scripts ----------
cat > scripts/generate_icons.sh <<'SH'
#!/usr/bin/env bash
# Runs flutter_launcher_icons after you've placed a 1024x1024 PNG in assets/icons/app_icon.png
set -e
dart run flutter_launcher_icons
SH
chmod +x scripts/generate_icons.sh

cat > scripts/build_release.sh <<'SH'
#!/usr/bin/env bash
set -e
flutter pub get
dart run build_runner build --delete-conflicting-outputs
flutter build appbundle --release
echo "Release bundle at build/app/outputs/bundle/release/app-release.aab"
SH
chmod +x scripts/build_release.sh

# ---------- move PRD + CONTEXT into docs/ ----------
if [ -f "../SpeakUp_Reading_PRD.docx" ]; then cp ../SpeakUp_Reading_PRD.docx docs/PRD.docx; fi
if [ -f "../CONTEXT.md" ]; then cp ../CONTEXT.md docs/CONTEXT.md; else
cat > docs/CONTEXT.md <<'MD'
# CONTEXT.md (placeholder — replace with the version from the starter package)
MD
fi

echo ""
echo "✅ Scaffold created at ./${ROOT}/"
echo ""
echo "Next steps:"
echo "  1. cd ${ROOT}"
echo "  2. flutter create --project-name ielts_reading_app --platforms=android --org com.morshed ."
echo "  3. flutter pub get"
echo "  4. flutterfire configure   # generates lib/firebase_options.dart"
echo "  5. Open in your IDE and point your AI agent at docs/PRD.docx + docs/CONTEXT.md"
