'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import {
  BookOpen, PenTool, Brain, Star, Download, ChevronRight,
  Zap, CheckCircle2, Mic, TrendingUp, Globe2, Award, Users,
  ArrowRight, Menu, X
} from 'lucide-react';

const STATS = [
  { value: '0', label: 'Active Learners' },
  { value: '0', label: 'App Store Rating' },
  { value: '0', label: 'Practice Passages' },
  { value: '0', label: 'Band Score Improvement' },
];

const FEATURES = [
  {
    icon: BookOpen,
    color: 'from-indigo-500 to-blue-600',
    bg: 'bg-indigo-50',
    iconColor: 'text-indigo-600',
    title: 'AI Reading Practice',
    desc: 'Unlimited authentic IELTS-style passages generated by AI, covering all academic topics — fresh every session.',
  },
  {
    icon: PenTool,
    color: 'from-emerald-500 to-teal-600',
    bg: 'bg-emerald-50',
    iconColor: 'text-emerald-600',
    title: 'Writing Task Trainer',
    desc: 'Task 1 & Task 2 prompts with instant AI feedback on coherence, vocabulary, grammar, and band score prediction.',
  },
  {
    icon: Mic,
    color: 'from-rose-500 to-pink-600',
    bg: 'bg-rose-50',
    iconColor: 'text-rose-600',
    title: 'Speaking Simulator',
    desc: 'Realistic speaking practice with AI examiner responses and detailed pronunciation & fluency analysis.',
  },
  {
    icon: Brain,
    color: 'from-violet-500 to-purple-600',
    bg: 'bg-violet-50',
    iconColor: 'text-violet-600',
    title: 'Smart Vocabulary',
    desc: 'Context-aware word learning with spaced repetition. Master academic vocabulary proven to boost your score.',
  },
  {
    icon: TrendingUp,
    color: 'from-amber-500 to-orange-600',
    bg: 'bg-amber-50',
    iconColor: 'text-amber-600',
    title: 'Progress Analytics',
    desc: 'Track your improvement over time with detailed performance charts and personalized weakness targeting.',
  },
  {
    icon: Globe2,
    color: 'from-cyan-500 to-sky-600',
    bg: 'bg-cyan-50',
    iconColor: 'text-cyan-600',
    title: 'Offline Mode',
    desc: 'Download practice sets and study anywhere, anytime — no internet required. Your progress syncs automatically.',
  },
];

const TESTIMONIALS = [
  {
    name: 'Ayesha Rahman',
    score: 'Band 8.0',
    location: 'Dhaka, Bangladesh',
    text: 'SpeakUp AI transformed my preparation. The reading passages are spot-on for actual IELTS difficulty. I improved from 6.5 to 8.0 in just 6 weeks!',
    avatar: 'A',
    color: 'bg-indigo-500',
  },
  {
    name: 'Tariq Mahmood',
    score: 'Band 7.5',
    location: 'Lahore, Pakistan',
    text: 'The AI writing feedback is incredibly detailed. It told me exactly why my essay scored lower and how to fix it. Worth every penny.',
    avatar: 'T',
    color: 'bg-emerald-500',
  },
  {
    name: 'Priya Nair',
    score: 'Band 8.5',
    location: 'Kochi, India',
    text: 'I used SpeakUp AI for 2 months and achieved 8.5 overall. The vocabulary builder and diagnostic tests are exceptional.',
    avatar: 'P',
    color: 'bg-violet-500',
  },
];

const DOWNLOAD_LINKS = {
  googlePlay: process.env.NEXT_PUBLIC_GOOGLE_PLAY_URL || '/downloads/speakup-ai.apk',
  appStore: process.env.NEXT_PUBLIC_APP_STORE_URL || '#download',
  apk: process.env.NEXT_PUBLIC_APK_DOWNLOAD_URL || '/downloads/speakup-ai.apk',
};

export default function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener('scroll', onScroll);
    return () => window.removeEventListener('scroll', onScroll);
  }, []);

  return (
    <div className="min-h-screen bg-white text-gray-900 overflow-x-hidden">
      {/* ── Navbar ──────────────────────────────────────────────── */}
      <header
        className={`fixed top-0 inset-x-0 z-50 transition-all duration-300 ${
          scrolled ? 'bg-white/90 backdrop-blur-md shadow-sm border-b border-gray-100' : 'bg-transparent'
        }`}
      >
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-indigo-600 to-violet-600">
              <Zap className="h-4 w-4 text-white" />
            </div>
            <span className="text-lg font-bold tracking-tight">SpeakUp AI</span>
          </div>

          {/* Desktop nav */}
          <nav className="hidden md:flex items-center gap-6">
            <a href="#features" className="text-sm font-medium text-gray-600 hover:text-gray-900 transition-colors">Features</a>
            <a href="#testimonials" className="text-sm font-medium text-gray-600 hover:text-gray-900 transition-colors">Reviews</a>
            <a href="#download" className="text-sm font-medium text-gray-600 hover:text-gray-900 transition-colors">Download</a>
            <Link href="/login" className="text-sm font-medium text-gray-500 hover:text-gray-700 transition-colors">Admin</Link>
          </nav>

          <a
            href="#download"
            id="nav-download-btn"
            className="hidden md:flex items-center gap-2 bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-700 hover:to-violet-700 text-white text-sm font-semibold rounded-full px-5 py-2 transition-all shadow-md hover:shadow-lg hover:shadow-indigo-200"
          >
            <Download className="h-4 w-4" />
            Download Free
          </a>

          {/* Mobile menu toggle */}
          <button
            className="md:hidden p-2 rounded-lg text-gray-600 hover:bg-gray-100"
            onClick={() => setMenuOpen(!menuOpen)}
            aria-label="Toggle menu"
          >
            {menuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}
          </button>
        </div>

        {/* Mobile menu */}
        {menuOpen && (
          <div className="md:hidden bg-white border-t border-gray-100 px-6 py-4 space-y-3">
            <a href="#features" onClick={() => setMenuOpen(false)} className="block text-sm font-medium text-gray-700 py-2">Features</a>
            <a href="#testimonials" onClick={() => setMenuOpen(false)} className="block text-sm font-medium text-gray-700 py-2">Reviews</a>
            <a href="#download" onClick={() => setMenuOpen(false)} className="block text-sm font-medium text-gray-700 py-2">Download</a>
            <Link href="/login" onClick={() => setMenuOpen(false)} className="block text-sm font-medium text-gray-500 py-2">Admin Login</Link>
            <a href="#download" id="mobile-download-btn" className="flex items-center justify-center gap-2 bg-gradient-to-r from-indigo-600 to-violet-600 text-white text-sm font-semibold rounded-full px-5 py-2.5 mt-2">
              <Download className="h-4 w-4" />
              Download Free
            </a>
          </div>
        )}
      </header>

      {/* ── Hero ──────────────────────────────────────────────────── */}
      <section className="relative pt-32 pb-24 px-6 overflow-hidden">
        {/* Background gradient */}
        <div className="absolute inset-0 bg-gradient-to-br from-indigo-50 via-white to-violet-50 pointer-events-none" />
        {/* Decorative blobs */}
        <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-gradient-to-bl from-indigo-100/60 to-transparent rounded-full blur-3xl pointer-events-none" />
        <div className="absolute bottom-0 left-0 w-[400px] h-[400px] bg-gradient-to-tr from-violet-100/60 to-transparent rounded-full blur-3xl pointer-events-none" />

        <div className="relative max-w-7xl mx-auto text-center">
          {/* Badge */}
          <div className="inline-flex items-center gap-2 bg-indigo-50 border border-indigo-100 rounded-full px-4 py-1.5 mb-6">
            <Award className="h-3.5 w-3.5 text-indigo-600" />
            <span className="text-xs font-semibold text-indigo-700 uppercase tracking-wide">#1 IELTS Prep App in South Asia</span>
          </div>

          <h1 className="text-5xl md:text-7xl font-extrabold text-gray-900 leading-tight tracking-tight mb-6">
            Ace Your IELTS with{' '}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-violet-600">
              AI-Powered
            </span>{' '}
            Practice
          </h1>

          <p className="text-xl md:text-2xl text-gray-600 max-w-3xl mx-auto leading-relaxed mb-10">
            Unlimited reading passages, intelligent writing feedback, and personalised study plans.
            Start your journey today and achieve your target band score.
          </p>

          {/* CTA Buttons */}
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 mb-14">
            <a
              href="#download"
              id="hero-primary-cta"
              className="flex items-center gap-2.5 bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-700 hover:to-violet-700 text-white font-bold rounded-2xl px-8 py-4 text-lg transition-all shadow-xl hover:shadow-2xl hover:shadow-indigo-300 hover:-translate-y-0.5"
            >
              <Download className="h-5 w-5" />
              Download Free – Android APK
              <ChevronRight className="h-5 w-5" />
            </a>
            <a
              href="#features"
              className="flex items-center gap-2 text-gray-700 font-semibold text-lg hover:text-indigo-700 transition-colors group"
            >
              See how it works
              <ArrowRight className="h-5 w-5 group-hover:translate-x-1 transition-transform" />
            </a>
          </div>

          {/* Stats bar */}
          <div className="inline-grid grid-cols-2 sm:grid-cols-4 gap-px bg-gray-200/80 rounded-2xl overflow-hidden shadow-sm max-w-3xl mx-auto">
            {STATS.map((stat) => (
              <div key={stat.label} className="bg-white px-6 py-4 text-center">
                <p className="text-2xl font-extrabold text-gray-900">{stat.value}</p>
                <p className="text-xs text-gray-500 mt-0.5">{stat.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Features ──────────────────────────────────────────────── */}
      <section id="features" className="py-24 px-6 bg-white">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-14">
            <p className="text-sm font-semibold text-indigo-600 uppercase tracking-widest mb-3">Everything You Need</p>
            <h2 className="text-4xl md:text-5xl font-extrabold text-gray-900 tracking-tight">
              Built for Band 9 Aspirants
            </h2>
            <p className="text-lg text-gray-500 mt-4 max-w-2xl mx-auto">
              Every feature is designed around what top IELTS scorers actually need — no fluff, no filler.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {FEATURES.map((f) => (
              <div
                key={f.title}
                className="group relative bg-white border border-gray-100 rounded-2xl p-6 hover:border-transparent hover:shadow-2xl hover:-translate-y-1 transition-all duration-300 overflow-hidden"
              >
                {/* Gradient hover bg */}
                <div className={`absolute inset-0 bg-gradient-to-br ${f.color} opacity-0 group-hover:opacity-5 transition-opacity duration-300`} />

                <div className={`inline-flex p-3 rounded-xl ${f.bg} mb-4`}>
                  <f.icon className={`h-6 w-6 ${f.iconColor}`} />
                </div>
                <h3 className="text-lg font-bold text-gray-900 mb-2">{f.title}</h3>
                <p className="text-sm text-gray-500 leading-relaxed">{f.desc}</p>

                <div className="mt-4 flex items-center gap-1.5 text-xs font-semibold text-indigo-600 opacity-0 group-hover:opacity-100 transition-opacity">
                  Learn more <ArrowRight className="h-3.5 w-3.5" />
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Why SpeakUp ─────────────────────────────────────────── */}
      <section className="py-24 px-6 bg-gradient-to-br from-slate-900 via-indigo-950 to-slate-900 relative overflow-hidden">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-0 left-1/4 w-[500px] h-[500px] bg-indigo-600/10 rounded-full blur-3xl" />
          <div className="absolute bottom-0 right-1/4 w-[400px] h-[400px] bg-violet-600/10 rounded-full blur-3xl" />
        </div>

        <div className="relative max-w-7xl mx-auto">
          <div className="text-center mb-14">
            <p className="text-sm font-semibold text-indigo-400 uppercase tracking-widest mb-3">Why SpeakUp AI?</p>
            <h2 className="text-4xl md:text-5xl font-extrabold text-white tracking-tight">
              The Smarter Way to Prepare
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-4xl mx-auto">
            {[
              'AI generates fresh passages daily — never repeat the same content',
              'Instant, examiner-level writing feedback in seconds',
              'Adaptive difficulty that grows with your skill level',
              'Full offline support — study on the go, anywhere',
              'Proven methods to help you achieve your target band',
              'Regular updates with new content every week',
            ].map((point) => (
              <div key={point} className="flex items-start gap-3">
                <CheckCircle2 className="h-5 w-5 text-emerald-400 shrink-0 mt-0.5" />
                <p className="text-gray-300 text-sm leading-relaxed">{point}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Testimonials ────────────────────────────────────────── */}
      <section id="testimonials" className="py-24 px-6 bg-gray-50">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-14">
            <p className="text-sm font-semibold text-indigo-600 uppercase tracking-widest mb-3">Student Success</p>
            <h2 className="text-4xl md:text-5xl font-extrabold text-gray-900 tracking-tight">
              Real Results, Real Students
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {TESTIMONIALS.map((t) => (
              <div key={t.name} className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm hover:shadow-md transition-shadow">
                <div className="flex items-center gap-1 mb-4">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="h-4 w-4 fill-amber-400 text-amber-400" />
                  ))}
                </div>
                <p className="text-gray-700 text-sm leading-relaxed mb-5">&ldquo;{t.text}&rdquo;</p>
                <div className="flex items-center gap-3">
                  <div className={`h-10 w-10 rounded-full ${t.color} flex items-center justify-center text-white font-bold text-sm`}>
                    {t.avatar}
                  </div>
                  <div>
                    <p className="font-semibold text-gray-900 text-sm">{t.name}</p>
                    <p className="text-xs text-gray-400">{t.score} · {t.location}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Download ────────────────────────────────────────────── */}
      <section id="download" className="py-24 px-6 bg-white">
        <div className="max-w-5xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 bg-indigo-50 border border-indigo-100 rounded-full px-4 py-1.5 mb-6">
            <Users className="h-3.5 w-3.5 text-indigo-600" />
            <span className="text-xs font-semibold text-indigo-700">Start learning today</span>
          </div>

          <h2 className="text-4xl md:text-6xl font-extrabold text-gray-900 tracking-tight mb-5">
            Start Your{' '}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-600 to-violet-600">
              Free
            </span>{' '}
            Journey
          </h2>

          <p className="text-lg text-gray-500 max-w-2xl mx-auto mb-12">
            Download SpeakUp AI now — completely free to start. No credit card required.
            Choose the APK that matches your Android device.
          </p>

          {/* Per-ABI APK cards */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-5 mb-8">
            {/* arm64-v8a — recommended */}
            <div className="relative flex flex-col items-center bg-gradient-to-br from-indigo-50 to-violet-50 border-2 border-indigo-200 rounded-2xl p-6 shadow-md hover:shadow-xl hover:-translate-y-1 transition-all duration-300">
              <span className="absolute -top-3 left-1/2 -translate-x-1/2 bg-gradient-to-r from-indigo-600 to-violet-600 text-white text-xs font-bold rounded-full px-3 py-1 shadow">
                ⭐ Recommended
              </span>
              <div className="mt-3 mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-indigo-500 to-violet-600 shadow-lg">
                <Download className="h-7 w-7 text-white" />
              </div>
              <h3 className="text-base font-bold text-gray-900 mb-1">arm64-v8a</h3>
              <p className="text-xs text-gray-500 mb-1">64-bit ARM · Modern phones</p>
              <p className="text-xs font-semibold text-indigo-600 mb-4">26.3 MB</p>
              <a
                id="apk-arm64-download"
                href="/downloads/app-arm64-v8a-release.apk"
                download="SpeakUpAI-arm64-v8a.apk"
                className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-700 hover:to-violet-700 text-white font-bold rounded-xl px-4 py-3 text-sm transition-all shadow hover:shadow-indigo-300"
              >
                <Download className="h-4 w-4" />
                Download
              </a>
            </div>

            {/* armeabi-v7a */}
            <div className="flex flex-col items-center bg-white border border-gray-200 rounded-2xl p-6 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300">
              <div className="mb-4 mt-3 flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-500 to-teal-600 shadow-lg">
                <Download className="h-7 w-7 text-white" />
              </div>
              <h3 className="text-base font-bold text-gray-900 mb-1">armeabi-v7a</h3>
              <p className="text-xs text-gray-500 mb-1">32-bit ARM · Older devices</p>
              <p className="text-xs font-semibold text-emerald-600 mb-4">24.1 MB</p>
              <a
                id="apk-armv7-download"
                href="/downloads/app-armeabi-v7a-release.apk"
                download="SpeakUpAI-armeabi-v7a.apk"
                className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-emerald-500 to-teal-600 hover:from-emerald-600 hover:to-teal-700 text-white font-bold rounded-xl px-4 py-3 text-sm transition-all shadow hover:shadow-emerald-200"
              >
                <Download className="h-4 w-4" />
                Download
              </a>
            </div>

            {/* x86_64 */}
            <div className="flex flex-col items-center bg-white border border-gray-200 rounded-2xl p-6 shadow-sm hover:shadow-xl hover:-translate-y-1 transition-all duration-300">
              <div className="mb-4 mt-3 flex h-14 w-14 items-center justify-center rounded-2xl bg-gradient-to-br from-amber-500 to-orange-600 shadow-lg">
                <Download className="h-7 w-7 text-white" />
              </div>
              <h3 className="text-base font-bold text-gray-900 mb-1">x86_64</h3>
              <p className="text-xs text-gray-500 mb-1">64-bit x86 · Emulators</p>
              <p className="text-xs font-semibold text-amber-600 mb-4">27.7 MB</p>
              <a
                id="apk-x86-download"
                href="/downloads/app-x86_64-release.apk"
                download="SpeakUpAI-x86_64.apk"
                className="w-full flex items-center justify-center gap-2 bg-gradient-to-r from-amber-500 to-orange-600 hover:from-amber-600 hover:to-orange-700 text-white font-bold rounded-xl px-4 py-3 text-sm transition-all shadow hover:shadow-amber-200"
              >
                <Download className="h-4 w-4" />
                Download
              </a>
            </div>
          </div>

          <p className="text-sm text-gray-400 mb-2">Version 1.0.0 · Requires Android 8.0+</p>
          <p className="text-xs text-gray-400">
            Not sure which to pick?{' '}
            <span className="font-semibold text-indigo-600">arm64-v8a</span> works on all modern Android phones (2017 and newer).
          </p>
        </div>
      </section>

      {/* ── Footer ──────────────────────────────────────────────── */}
      <footer className="bg-gray-50 border-t border-gray-100 py-10 px-6">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-gradient-to-br from-indigo-600 to-violet-600">
              <Zap className="h-3.5 w-3.5 text-white" />
            </div>
            <span className="font-bold text-gray-900">SpeakUp AI</span>
          </div>
          <p className="text-sm text-gray-400">© 2025 SpeakUp AI. All rights reserved.</p>
          <div className="flex items-center gap-4">
            <a href="#" className="text-sm text-gray-400 hover:text-gray-600 transition-colors">Privacy</a>
            <a href="#" className="text-sm text-gray-400 hover:text-gray-600 transition-colors">Terms</a>
            <Link href="/login" className="text-sm text-gray-400 hover:text-indigo-600 transition-colors">Admin</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
